name: Consumer CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  python-ci:
    uses: karthika-u07/engineering-workflows/.github/workflows/python-ci.yml@main

    with:
      python-version: "3.11"

    secrets:
      training-secret: ${{ secrets.TRAINING_SECRET }}

  show-result:
    needs: python-ci
    runs-on: ubuntu-latest

    steps:
      - name: Show reusable workflow output
        run: |
          echo "Python version reported by reusable workflow:"
          echo "${{ needs.python-ci.outputs.python-version-used }}"
