name: Consumer CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  python-ci:
    uses: karthika-u07/engineering-workflows/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.11"
