name: GitHub Actions Jobs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Code quality check
        run: echo "Running code quality checks"

      - name: Show quality job
        run: echo "This is the code-quality job"

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Security check
        run: echo "Running security checks"

      - name: Show security job
        run: echo "This is the security job"